name: Test & Release
on: [push, pull_request]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  tests:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '18', '20' ]
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9.1.4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - run: pnpm install

      - run: pnpm build

      - run: pnpm test:packages

      - run: pnpm lint

      - run: pnpm lint:attw

      - run: pnpm lint:publint
  release:
    name: Release
    if: ${{ github.event_name == 'push' && (github.ref_name == 'main' || github.ref_name == 'beta') }}
    needs: tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '18' ]
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9.1.4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          # https://github.com/pnpm/pnpm/issues/3141
          registry-url: 'https://registry.npmjs.org'

      - run: pnpm install

      - run: pnpm release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
